export const GET_ALL_CARS = 'GET_ALL_CARS';
export const GET_FEATURED_CARS = 'GET_FEATURED_CARS';
export const SET_SLIDERS = 'SET_SLIDERS';

export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const GET_ALL_BODYTYPES = 'GET_ALL_BODYTYPES';